<?php
	class CountryDb {

		public function get_country_list() {
			return $this->Countries;
		}

		public function get_residence_status_list() {
			return $this->ResidenceStatus;
		}

		private $ResidenceStatus = array (
				'Permanent Resident',
				'Employment',
				'Student',
				'Tourist'
			);

		private $Countries = array (
			'Afghanistan',
			'Albania',
			'Algeria',
			'Andorra',
			'Angola',
			'Antigua & Barbuda',
			'Argentina',
			'Armenia',
			'Australia',
			'Austria',
			'Azerbaijan',
			'Bahamas',
			'Bahrain',
			'Bangladesh',
			'Barbados',
			'Belarus',
			'Belgium',
			'Belize',
			'Benin',
			'Bhutan',
			'Bolivia',
			'Bosnia & Herzegovina',
			'Botswana',
			'Brazil',
			'Brunei',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Cabo Verde',
			'Cambodia',
			'Cameroon',
			'Canada',
			'Central African Republic',
			'Chad',
			'Chile',
			'China',
			'Colombia',
			'Comoros',
			'Costa Rica',
			'Croatia',
			'Cuba',
			'Cyprus',
			'Czech Republic',
			'Cote d Ivoire',
			'Democratic Republic of the Congo',
			'Denmark',
			'Djibouti',
			'Dominica',
			'Dominican Republic',
			'Ecuador',
			'Egypt',
			'El Salvador',
			'Equatorial Guinea',
			'Eritrea',
			'Estonia',
			'Ethiopia',
			'Federated States of Micronesia',
			'Fiji',
			'Finland',
			'France',
			'Gabon',
			'Gambia',
			'Georgia',
			'Germany',
			'Ghana',
			'Greece',
			'Grenada',
			'Guatemala',
			'Guinea',
			'Guinea-Bissau',
			'Guyana',
			'Haiti',
			'Holy See',
			'Honduras',
			'Hong Kong',
			'Hungary',
			'Iceland',
			'India',
			'Indonesia',
			'Iran',
			'Iraq',
			'Ireland',
			'Israel',
			'Italy',
			'Jamaica',
			'Jordan',
			'Kazakhstan',
			'Kenya',
			'Kiribati',
			'Kosovo ',
			'Kuwait',
			'Kyrgyzstan',
			'Laos',
			'Latvia',
			'Lebanon',
			'Lesotho',
			'Liberia',
			'Libya',
			'Liechtenstein',
			'Lithuania',
			'Luxembourg',
			'Macau',
			'Macedonia',
			'Madagascar',
			'Malawi',
			'Malaysia',
			'Maldives',
			'Mali',
			'Malta',
			'Marshall Islands',
			'Mauritania',
			'Mauritius',
			'Mexico',
			'Moldova',
			'Monaco',
			'Mongolia',
			'Montenegro',
			'Morocco',
			'Mozambique',
			'Myanmar',
			'Namibia',
			'Nauru',
			'Nepal',
			'Netherlands',
			'New Zealand',
			'Nicaragua',
			'Niger',
			'Nigeria',
			'North Korea',
			'Norway',
			'Oman',
			'Pakistan',
			'Palau',
			'Palestine',
			'Panama',
			'Papua New Guinea',
			'Paraguay',
			'Peru',
			'Philippines',
			'Poland',
			'Portugal',
			'Qatar',
			'Republic of the Congo',
			'Romania',
			'Russia',
			'Rwanda',
			'Saint Kitts & Nevis',
			'Saint Lucia',
			'Saint Vincent & the Grenadines',
			'Samoa',
			'San Marino',
			'Sao Tome & Principe',
			'Saudi Arabia',
			'Senegal ',
			'Serbia',
			'Seychelles',
			'Sierra Leone',
			'Singapore',
			'Slovakia',
			'Slovenia',
			'Solomon Islands',
			'Somalia',
			'Sotuh Korea',
			'South Africa',
			'South Sudan',
			'Spain',
			'Sri Lanka',
			'Sudan',
			'Suriname',
			'Swaziland',
			'Sweden',
			'Switzerland ',
			'Syria',
			'Taiwan',
			'Tajikistan',
			'Tanzania',
			'Thailand',
			'Timor-Leste',
			'Togo',
			'Tonga',
			'Trinidad & Tobago',
			'Tunisia',
			'Turkey',
			'Turkmenistan',
			'Tuvalu',
			'Uganda',
			'Ukraine',
			'United Arab Emirates',
			'United Kingdom',
			'United States',
			'Uruguay',
			'Uzbekistan',
			'Vanuatu',
			'Venezuela',
			'Vietnam',
			'Yemen',
			'Zambia',
			'Zimbabwe'
		);
		private $Territories = array (
			'American Samoa',
			'Anguilla',
			'Aruba',
			'Bermuda',
			'British Virgin Islands',
			'Cayman Islands',
			'Cook Islands',
			'Curaçao',
			'Falkland Islands',
			'Faroe Islands',
			'French Guiana',
			'French Polynesia',
			'Gibraltar',
			'Greenland',
			'Guadeloupe',
			'Guam',
			'Martinique',
			'Mayotte',
			'Montserrat',
			'New Caledonia',
			'Niue',
			'Pitcairn Islands',
			'Puerto Rico',
			'Saint Barthelemy',
			'Saint Helena',
			'Saint Martin',
			'Saint Pierre & Miquelon',
			'Sint Maarten',
			'Svalbard',
			'Tokelau',
			'Turks & Caicos Islands',
			'U.S. Virgin Islands',
			'Wallis & Futuna'
		);
		private $Disputed_Regions = array (
			'Abkhazia',
			'Nagarno-Karabakh',
			'Somaliland',
			'South Ossetia',
			'Transnistria',
			'Turkish Republic of Northern Cyprus',
			'Western Sahara'
		);
		private $Territories_Uninhabited = array (
			'Akrotiri',
			'Antarctica',
			'Ashmore & Cartier Islands',
			'Baker Island',
			'Bouvet Island',
			'British Indian Ocean Territory',
			'Christmas Island',
			'Clipperton Island',
			'Cocos (Keeling) Islands',
			'Coral Sea Islands',
			'Dhekelia',
			'French Southern & Antarctic Lands',
			'Guernsey',
			'Heard Island & McDonald Islands',
			'Howland Island',
			'Isle of Man',
			'Jan Mayen',
			'Jarvis Island',
			'Jersey',
			'Johnston Atoll',
			'Kingman Reef',
			'Midway Islands',
			'Navassa Island',
			'Norfolk Island',
			'Northern Mariana Islands',
			'Palmyra Atoll',
			'Paracel Islands',
			'South Georgia & the South Sandwich Islands',
			'Spratly Islands',
			'Wake Island'
		);
	}

?>